In [23]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts

          username  phone_number  ... last_message_date is_online
0          jfound0  730-393-9220  ...         8/12/2020     False
1          gsoule1  244-674-2095  ...         1/26/2020      True
2       ehendrich2  324-800-7471  ...         3/11/2022     False
3        rkiernan3  874-302-6761  ...         6/11/2021      True
4           bcopp4  270-836-3899  ...         8/21/2021     False
..             ...           ...  ...               ...       ...
995      delcouxrn  599-998-2051  ...         3/20/2021      True
996  cleadbeaterro  133-487-1114  ...         11/7/2020      True
997      lbaynomrp  847-815-7187  ...          3/9/2022     False
998     sarntzenrq  650-129-3220  ...        11/21/2022      True
999    rkingcottrr  433-656-5751  ...          3/6/2020      True

[1000 rows x 9 columns]

In [27]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts.head()

     username  phone_number  ... last_message_date is_online
0     jfound0  730-393-9220  ...         8/12/2020     False
1     gsoule1  244-674-2095  ...         1/26/2020      True
2  ehendrich2  324-800-7471  ...         3/11/2022     False
3   rkiernan3  874-302-6761  ...         6/11/2021      True
4      bcopp4  270-836-3899  ...         8/21/2021     False

[5 rows x 9 columns]

In [28]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts.head(10)

     username  phone_number  ... last_message_date is_online
0     jfound0  730-393-9220  ...         8/12/2020     False
1     gsoule1  244-674-2095  ...         1/26/2020      True
2  ehendrich2  324-800-7471  ...         3/11/2022     False
3   rkiernan3  874-302-6761  ...         6/11/2021      True
4      bcopp4  270-836-3899  ...         8/21/2021     False
5   adurrant5  287-651-4316  ...         8/24/2021     False
6    pbowley6  381-752-8649  ...         8/31/2022     False
7   etooting7  514-659-4184  ...         8/31/2020      True
8   talforde8  596-111-1142  ...         7/14/2022     False
9     chiers9  402-978-7073  ...         12/4/2021     False

[10 rows x 9 columns]

In [30]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts.tail()

          username  phone_number  ... last_message_date is_online
995      delcouxrn  599-998-2051  ...         3/20/2021      True
996  cleadbeaterro  133-487-1114  ...         11/7/2020      True
997      lbaynomrp  847-815-7187  ...          3/9/2022     False
998     sarntzenrq  650-129-3220  ...        11/21/2022      True
999    rkingcottrr  433-656-5751  ...          3/6/2020      True

[5 rows x 9 columns]

In [31]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts.tail(10)

          username  phone_number  ... last_message_date is_online
990      dcrudgeri  828-160-5337  ...          7/6/2022     False
991     pgarrattrj  193-514-1841  ...          5/3/2021     False
992    smacavddyrk  425-439-6423  ...         6/26/2021     False
993    wkimberlyrl  172-353-9166  ...         3/12/2022      True
994        fmeusrm  263-413-2939  ...         6/14/2021     False
995      delcouxrn  599-998-2051  ...         3/20/2021      True
996  cleadbeaterro  133-487-1114  ...         11/7/2020      True
997      lbaynomrp  847-815-7187  ...          3/9/2022     False
998     sarntzenrq  650-129-3220  ...        11/21/2022      True
999    rkingcottrr  433-656-5751  ...          3/6/2020      True

[10 rows x 9 columns]

In [43]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')
telegram_accounts.shape

(1000, 9)

In [53]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')

pd.set_option('display.min_row', 50)

telegram_accounts

           username  phone_number  ... last_message_date is_online
0           jfound0  730-393-9220  ...         8/12/2020     False
1           gsoule1  244-674-2095  ...         1/26/2020      True
2        ehendrich2  324-800-7471  ...         3/11/2022     False
3         rkiernan3  874-302-6761  ...         6/11/2021      True
4            bcopp4  270-836-3899  ...         8/21/2021     False
5         adurrant5  287-651-4316  ...         8/24/2021     False
6          pbowley6  381-752-8649  ...         8/31/2022     False
7         etooting7  514-659-4184  ...         8/31/2020      True
8         talforde8  596-111-1142  ...         7/14/2022     False
9           chiers9  402-978-7073  ...         12/4/2021     False
10       hkalinskya  994-997-9390  ...         12/8/2021      True
11    gmassingberdb  784-486-3238  ...         9/20/2020      True
12       ulagrangec  905-357-4880  ...         1/20/2022      True
13          gellsed  564-994-1369  ...         6/15/2020     False
14         wthomase  901-752-9166  ...         8/21/2021     False
15       swatermanf  782-741-7831  ...          1/6/2020     False
16         rcalleyg  964-315-9812  ...          5/1/2020      True
17    krutherfoordh  398-422-8896  ...          2/6/2022     False
18     fmacwilliami  543-136-6394  ...          1/8/2021      True
19          csayrej  604-315-4502  ...         5/29/2020     False
20         cesseryk  206-587-3125  ...         11/3/2022      True
21         adrydenl  726-434-3370  ...        10/11/2021     False
22       omowsdellm  260-580-5499  ...         9/28/2020      True
23        dschurign  884-344-2273  ...         8/20/2021      True
24         lmarcuso  860-346-8461  ...         2/23/2022     False
..              ...           ...  ...               ...       ...
975    amaggorinir3  390-511-4266  ...         1/23/2021     False
976      kblizardr4  138-800-8436  ...        12/26/2022      True
977      lduffellr5  471-458-5839  ...         3/24/2022      True
978   bbeddinghamr6  425-477-8956  ...         5/21/2021     False
979       bvawtonr7  389-786-3364  ...         3/15/2021     False
980        acruftr8  685-333-3199  ...        11/11/2021     False
981        jduleyr9  592-522-6323  ...          6/6/2020      True
982         nfairra  239-656-1526  ...          5/1/2020     False
983      adogertyrb  600-725-0758  ...         3/24/2022      True
984      ocawthryrc  617-661-7985  ...         6/11/2022      True
985    kfrederickrd  680-812-1989  ...        12/21/2020     False
986        smericre  181-229-6046  ...         12/1/2021     False
987      mclemoesrf  470-955-9365  ...         8/25/2020      True
988       yfannonrg  948-378-7577  ...          1/5/2022      True
989  slethebridgerh  611-153-7333  ...          7/5/2021     False
990       dcrudgeri  828-160-5337  ...          7/6/2022     False
991      pgarrattrj  193-514-1841  ...          5/3/2021     False
992     smacavddyrk  425-439-6423  ...         6/26/2021     False
993     wkimberlyrl  172-353-9166  ...         3/12/2022      True
994         fmeusrm  263-413-2939  ...         6/14/2021     False
995       delcouxrn  599-998-2051  ...         3/20/2021      True
996   cleadbeaterro  133-487-1114  ...         11/7/2020      True
997       lbaynomrp  847-815-7187  ...          3/9/2022     False
998      sarntzenrq  650-129-3220  ...        11/21/2022      True
999     rkingcottrr  433-656-5751  ...          3/6/2020      True

[1000 rows x 9 columns]

In [54]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')

pd.set_option('display.max_row', 5)

telegram_accounts

        username  phone_number  ... last_message_date is_online
0        jfound0  730-393-9220  ...         8/12/2020     False
1        gsoule1  244-674-2095  ...         1/26/2020      True
..           ...           ...  ...               ...       ...
998   sarntzenrq  650-129-3220  ...        11/21/2022      True
999  rkingcottrr  433-656-5751  ...          3/6/2020      True

[1000 rows x 9 columns]

In [55]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')

pd.set_option('display.max_column', 5)

telegram_accounts

        username  phone_number  ... last_message_date is_online
0        jfound0  730-393-9220  ...         8/12/2020     False
1        gsoule1  244-674-2095  ...         1/26/2020      True
..           ...           ...  ...               ...       ...
998   sarntzenrq  650-129-3220  ...        11/21/2022      True
999  rkingcottrr  433-656-5751  ...          3/6/2020      True

[1000 rows x 9 columns]

In [56]:
import pandas as pd

telegram_accounts = pd.read_csv(r'C:\Users\dell\Desktop\img\MOCK_DATA.csv')

pd.reset_option('^display.', silent=True)

telegram_accounts

          username  phone_number  ... last_message_date is_online
0          jfound0  730-393-9220  ...         8/12/2020     False
1          gsoule1  244-674-2095  ...         1/26/2020      True
2       ehendrich2  324-800-7471  ...         3/11/2022     False
3        rkiernan3  874-302-6761  ...         6/11/2021      True
4           bcopp4  270-836-3899  ...         8/21/2021     False
..             ...           ...  ...               ...       ...
995      delcouxrn  599-998-2051  ...         3/20/2021      True
996  cleadbeaterro  133-487-1114  ...         11/7/2020      True
997      lbaynomrp  847-815-7187  ...          3/9/2022     False
998     sarntzenrq  650-129-3220  ...        11/21/2022      True
999    rkingcottrr  433-656-5751  ...          3/6/2020      True

[1000 rows x 9 columns]